name: budget_manager
description: Portal administrativo de orçamentos.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_modular: ^6.3.4
  cupertino_icons: ^1.0.6
  transparent_image: ^2.0.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  supabase_flutter: ^2.5.11
  localstorage: ^5.0.0
  shared_preferences: ^2.3.1
  dio: ^5.5.0+1
  timeago: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true